### ISSUE TITLE
notification for UI designers

### ISSUE THREAD

**Issue by zisen01** [CMPUT301W19T13/iBOOKit#4]
hi UI designers, I have just pushed a debugged version code on the github, there is few things that I want you to keep in mind when developing the UI:
1. the png files can only contain numbers, lowercase characters and underscore, or you will get bug like this:
E:\cmput301\iBOOKit\code\app\src\main\res\drawable-hdpi\myShelf.png: Error: 'S' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
I changed the name from "myShelf.png" to "my_shelf.png" in all related folders.

2. if you want to add some comment in xml, use , else the build will complan syntax error in xml files

3. since your classes used for the UI are under view folder, you should add .view. infront of the classname when delearing them in the AndroidManifest.xml

other than these, the UI is good, it looks nice by the way. I did some other minor bug fixing related the the things that I mentioned above, but the things that I want your guys to know before further development is listed above, feel free to tell me if anything I said wasn't right. I will test some fore specific parts as well as do some coding tomorrow.

**Comment by ChongzhengChen** [comment]
Yup thanks
gotta be more careful on naming staff in the future

**Comment by RitvikKhanna** [comment]
Done
